# This workflow will run some unit tests.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Unit tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Test with pytest
      run: |
        module load anaconda3/2020.11
        conda env create -f env.yml
        python testmaterial.py
        python testshape.py
        python testmeshbuilder.py
        python testmeshgenerator.py
